---
- name: Test Ansible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print Test Message
      debug:
        msg: "Hello, This is Ansible running from docker. Since you are getting this message, your test is successful! Yeah!"